In [57]:

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [58]:
df = pd.read_csv('Boston.csv')
epochs = 1000
learning_rate = 0.01

In [59]:
df.head()

,Crime Rate,Residential Proportion,non-retail business acres/Town,Charles River,NO2 concentration,Average Rooms/Dwelling.,Prior Built Units Proportion,Distance to Employment Centres,Radial Highways Distance,ValueProperty/tax rate,Teacher/town,blacks/town,Lower Status Percent,median home price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [60]:
train_df, test_df = train_test_split(df, test_size=0.3, random_state=42)

X = train_df[['Distance to Employment Centres', 'ValueProperty/tax rate']].values
y = train_df['median home price'].values

X_test = test_df[['Distance to Employment Centres', 'ValueProperty/tax rate']].values
y_test = test_df['median home price'].values

scaler = StandardScaler()
X = scaler.fit_transform(X)

DOT PRODUCT

In [61]:
def dot_product(a, b):
    return sum(a[i] * b[i] for i in range(len(a)))

Cost Function

In [62]:
def cost_function(X, y, w, b):
    cost = 0
    n = len(X)
    for i in range(n):
        y_pred = dot_product(w, X[i]) + b
        cost += (y_pred - y[i]) ** 2
    return cost / n

BATCH GD

In [63]:
def batch_gd(X,y,weights,bias,learning_rate):
    for epoch in range(epochs):
        total_error=0
        dw = [0.0]*len(weights)
        db=0.0

        for i in range(len(X)):
            y_pred=dot_product(weights,X[i])+bias

            error=y_pred-y[i]

            for j in range(len(weights)):
                dw[j]+=error*X[i][j]
            db+=error
        
        for j in range(len(weights)):
            weights[j]-=(learning_rate*dw[j])/len(X)
        bias-=(learning_rate*db)/len(X)

        if (epoch%100==0):
            cost=cost_function(X,y,weights,bias)
            print(f"Epoch {epoch}, Cost: {cost:.4f}")

Stochastic GD

In [64]:
def stochastic_gd(X, y, weights, bias, learning_rate):
    for epoch in range(epochs):
        for i in range(len(X)):
            y_pred = dot_product(weights, X[i]) + bias
            error = y_pred - y[i]

            for j in range(len(weights)):
                weights[j] -= learning_rate * error * X[i][j]
            bias -= learning_rate * error

        if epoch % 100 == 0:
            cost = cost_function(X, y, weights, bias)
            print(f"Epoch {epoch}, Cost: {cost:.4f}")

MINI BATCH GD

In [65]:
def mini_batch_gd(X, y, weights, bias, learning_rate, batch_size=32):
    num_samples = len(X)

    for epoch in range(epochs):
        indices = np.arange(num_samples)
        np.random.shuffle(indices)
        X = X[indices]
        y = y[indices]

        for start in range(0, num_samples, batch_size):
            end = min(start + batch_size, num_samples)
            X_batch = X[start:end]
            y_batch = y[start:end]

            dw = [0.0] * len(weights)
            db = 0.0

            for i in range(len(X_batch)):
                y_pred = dot_product(weights, X_batch[i]) + bias
                error = y_pred - y_batch[i]

                for j in range(len(weights)):
                    dw[j] += error * X_batch[i][j]
                db += error

            for j in range(len(weights)):
                weights[j] -= (learning_rate * dw[j]) / len(X_batch)
            bias -= (learning_rate * db) / len(X_batch)

        if epoch % 100 == 0:
            cost = cost_function(X, y, weights, bias)
            print(f"Epoch {epoch}, Cost: {cost:.4f}")

In [66]:
df.head()

,Crime Rate,Residential Proportion,non-retail business acres/Town,Charles River,NO2 concentration,Average Rooms/Dwelling.,Prior Built Units Proportion,Distance to Employment Centres,Radial Highways Distance,ValueProperty/tax rate,Teacher/town,blacks/town,Lower Status Percent,median home price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [67]:
def test_model(X_test, y_test, weights, bias):
    y_pred_test = [dot_product(weights, x) + bias for x in X_test]
    cost_test = cost_function(X_test, y_test, weights, bias)
    return cost_test/len(X_test)

TRAINING AND TESTING

In [68]:
weights = [0.0] * X.shape[1]
bias = 0.0

print("Batch Gradient Descent")
batch_gd(X, y, weights, bias, learning_rate)

print(f"Test Cost: {test_model(X_test, y_test, weights, bias):.4f}")


print("\nStochastic Gradient Descent")
stochastic_gd(X, y, weights, bias, learning_rate)

print(f"Test Cost: {test_model(X_test, y_test, weights, bias):.4f}")

print("\nMini Batch Gradient Descent")
mini_batch_gd(X, y, weights, bias, learning_rate, batch_size=32)

print(f"Test Cost: {test_model(X_test, y_test, weights, bias):.4f}")

Batch Gradient Descent
Epoch 0, Cost: 606.6242
Epoch 100, Cost: 141.6620
Epoch 200, Cost: 79.8630
Epoch 300, Cost: 71.3938
Epoch 400, Cost: 70.1686
Epoch 500, Cost: 69.9687
Epoch 600, Cost: 69.9282
Epoch 700, Cost: 69.9175
Epoch 800, Cost: 69.9140
Epoch 900, Cost: 69.9128
Test Cost: 23443.4769

Stochastic Gradient Descent
Epoch 0, Cost: 72.0320
Epoch 100, Cost: 71.2717
Epoch 200, Cost: 71.2717
Epoch 300, Cost: 71.2717
Epoch 400, Cost: 71.2717
Epoch 500, Cost: 71.2717
Epoch 600, Cost: 71.2717
Epoch 700, Cost: 71.2717
Epoch 800, Cost: 71.2717
Epoch 900, Cost: 71.2717
Test Cost: 17369.6298

Mini Batch Gradient Descent
Epoch 0, Cost: 484.4906
Epoch 100, Cost: 69.9982
Epoch 200, Cost: 70.1031
Epoch 300, Cost: 69.9232
Epoch 400, Cost: 69.9496
Epoch 500, Cost: 69.9677
Epoch 600, Cost: 70.0264
Epoch 700, Cost: 69.9604
Epoch 800, Cost: 69.9153
Epoch 900, Cost: 69.9391
Test Cost: 23625.5497